### PR TITLE
[Migrations] Add migrations adding closed_issues and closed_pull_request...

### PR DESCRIPTION
**Pull request by k0nserv**
...s to github_pod_metrics

### CODE REVIEW

**Comment by k0nserv** [comment]
Preparation for https://github.com/CocoaPods/metrics.cocoapods.org/issues/22

**Comment by segiddins** [comment]
\c @floere

**Comment by orta** [comment]
this looks good to me

**Comment by orta** [comment]
wait this needs a thing upping the potential number of migrations

**Comment by orta** [comment]
https://github.com/CocoaPods/Humus/blob/master/lib/migrate.rb#L28

**Comment by orta** [comment]
Deployed, and migrated.

```
~/s/h/S/Humus  $ heroku run bundle exec rake db:migrate                                                                                                                                              master
Running `bundle exec rake db:migrate` attached to terminal... up, run.4925
Are you very very sure what you are doing? very/no/maybe
very
Are you really really sure? really/naah
really
Last chance: Absolutely sure? absolutely/nope
absolutely
I, [2015-03-17T14:00:13.468676 #3]  INFO -- : (0.002131s) SET standard_conforming_strings = ON
```

**Pull request merged**
